name: kakehashi-appointment2
root: /Users/yokotsukanao/src/github.com/yokonao/kakehashi-appointment2

on_project_start: code .

on_project_exit: docker compose down

windows:
  - main:
      synchronize: after
      panes:
        - terminal:
          - sleep 10
          - bin/rails db:migrate RAILS_ENV=development
          - git status
  - frontend: bin/webpack-dev-server
  - backend: bin/rails s
  - database: docker compose up
  - logs: tail -f log/development.log
