version: "3.8"
services:
  db:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgresql
      POSTGRES_USER: postgresql
      POSTGRES_DB: postgresql_development
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: kakehashi-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

volumes:
  kakehashi-data:
    driver: local
