version: "3.8"
services:
  db:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgresql
      POSTGRES_USER: postgresql
      POSTGRES_DB: postgresql_development
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: kakehashi-data-2
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

volumes:
  kakehashi-data-2:
    driver: local
