default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: postgresql
  password: postgresql
  database: kakehashi-appointment2_development
  host: 127.0.0.1

test:
  <<: *default
  username: postgresql
  password: postgresql
  database: kakehashi-appointment2_test
  host: 127.0.0.1

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: kakehashi-appointment_production
  adapter: postgresql
  encoding: unicode
  pool: 5
